name: code-ranker
on:
  pull_request:
  push:
jobs:
  code-ranker:
    uses: code-ranker-com/actions/.github/workflows/report.yml@v1
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      security-events: write
